name: CI/CD Pipeline with docker(Build - Push - Deploy to EC2 - Test) - 
# proj : Dockerized Application CI/CD with GitHub Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  docker-build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: github-cicd-webapp
        run: npm install

      - name: Run tests
        working-directory: github-cicd-webapp
        run: npm test      

      # Build image
      - name: Build Docker image
        working-directory: github-cicd-webapp
        run: docker build -t chandana009/webapp-ci-cd:${{ github.sha }} .

      # Test container locally (optional but good practice)
      - name: Run container locally for test
        working-directory: github-cicd-webapp
        run: |
          docker run --rm -d -p 3000:3000 chandana009/webapp-ci-cd:${{ github.sha }}
          sleep 5

      - name: Test app locally
        working-directory: github-cicd-webapp
        run: curl -f http://localhost:3000

      # Login to Docker Hub
    #  - name: Login to Docker Hub
    #    run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push image
      - name: Push Docker image
        working-directory: github-cicd-webapp
        run: docker push chandana009/webapp-ci-cd:${{ github.sha }}

      # Deploy on EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull chandana009/webapp-ci-cd:${{ github.sha }}
            docker stop webapp || true
            docker rm webapp || true
            docker run -d --name webapp -p 3000:3000 chandana009/webapp-ci-cd:${{ github.sha }}

      # Test application on EC2
      - name: Test app on EC2
        run: curl -f http://${{ secrets.EC2_HOST }}:3000
        
      # Deploy on EC2 via SSH with rollback logic
      # - name: Deploy to EC2 with rollback
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USER }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       IMAGE=chandana009/webapp-ci-cd:${{ github.sha }}
      #       OLD_IMAGE=$(docker inspect webapp --format='{{.Config.Image}}' 2>/dev/null || echo "none")
      
      #       docker pull $IMAGE
      
      #       docker stop webapp || true
      #       docker rm webapp || true
      
      #       docker run -d --name webapp -p 3000:3000 $IMAGE
      
      #       sleep 5
      
      #       if ! curl -f http://localhost:3000; then
      #         echo "New version failed, rolling back..."
      #         docker stop webapp || true
      #         docker rm webapp || true
      #         docker run -d --name webapp -p 3000:3000 $OLD_IMAGE
      #         exit 1
      #       else
      #         echo "Deployment successful - Rollback"
      #       fi

      
        
