name: Multi-Environment CI/CD

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: github-cicd-webapp
        run: npm install

      - name: Run tests
        working-directory: github-cicd-webapp
        run: npm test      

      # Build image
      - name: Build Docker image
        working-directory: github-cicd-webapp
        run: docker build -t chandana009/webapp-ci-cd:${{ github.sha }} .

      # Test container locally (optional but good practice)
      - name: Run container locally for test
        working-directory: github-cicd-webapp
        run: |
          docker run --rm -d -p 3000:3000 chandana009/webapp-ci-cd:${{ github.sha }}
          sleep 5

      - name: Test app locally
        working-directory: github-cicd-webapp
       # run: curl -f http://localhost:3000
        run: curl -f http://${{ secrets.EC2_HOST }}:3000


#      - name: Login to DockerHub
#        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push image
        working-directory: github-cicd-webapp
        run: docker push chandana009/webapp-ci-cd:${{ github.sha }}

  deploy-dev:
    needs: build
    if: github.ref_name == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DEV
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull chandana009/webapp-ci-cd:${{ github.sha }}
            docker stop webapp || true
            docker rm webapp || true
            docker run -d --name webapp -p 3000:3000 chandana009/webapp-ci-cd:${{ github.sha }}

  deploy-staging:
    needs: build
    if: github.ref_name == 'staging'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to STAGING
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull chandana009/webapp-ci-cd:${{ github.sha }}
            docker stop webapp || true
            docker rm webapp || true
            docker run -d --name webapp -p 3000:3000 chandana009/webapp-ci-cd:${{ github.sha }}

  deploy-prod:
    needs: build
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to PROD
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull chandana009/webapp-ci-cd:${{ github.sha }}
            docker stop webapp || true
            docker rm webapp || true
            docker run -d --name webapp -p 3000:3000 chandana009/webapp-ci-cd:${{ github.sha }}

      - name: Test app on EC2
        run: curl -f http://${{ secrets.EC2_HOST }}:3000

